// <auto-generated />
using ImpoTrack.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImpoTrack.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ImpoTrack.Server.ComprobanteFiscal", b =>
                {
                    b.Property<int>("ComprobanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ComprobanteId"));

                    b.Property<double>("Itbis18")
                        .HasColumnType("double");

                    b.Property<double>("Monto")
                        .HasColumnType("double");

                    b.Property<string>("NCF")
                        .HasColumnType("longtext");

                    b.Property<string>("RncCedula")
                        .HasColumnType("longtext");

                    b.HasKey("ComprobanteId");

                    b.ToTable("ComprobantesFiscales");
                });

            modelBuilder.Entity("ImpoTrack.Server.Contribuyente", b =>
                {
                    b.Property<int>("ContribuyenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContribuyenteId"));

                    b.Property<string>("Estatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("RncCedula")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("ContribuyenteId");

                    b.ToTable("Contribuyentes");
                });
#pragma warning restore 612, 618
        }
    }
}
